name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build Docker image
        run: docker build -t node-rest-api .

      - name: Tag Docker image
        run: docker tag node-rest-api salmansyyd/node-rest-api:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push salmansyyd/node-rest-api:latest

      - name: Run Docker container
        run: docker run -d -p 3000:3000 node-rest-api
